% This improved correction will be added later
function o_correctedCameraResponse = HDM_OFT_CameraResponseCorrectionStep2...
    (i_estimatedCameraResponse, ...
    i_image, ...
    i_SceneIllumination, ...
    i_PatchSet)

    o_correctedCameraResponse = i_estimatedCameraResponse;

